#!/bin/bash

TEST_MODULE_DIR="/tmp/modularized_test/test_modules"
BLADE_URL=https://qe-test.s3.amazonaws.com/chaosblade-1.0.0-linux-amd64.tar.gz
EXP_INTERVAL=300
DURATION=86400
EXP_COUNT=3
SUDO_PERMISSION=true
EXPERIMENTS=mem_load #cpu_load,mem_load,disk_burn,process_stop,process_kill,network_delay,service_restart,disk_fill
